// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
package currency

// CAD is the Canadian Dollar Currency
var CAD = Currency{
	Code:      "CAD",
	Number:    124,
	Symbol:    '$',
	Decimal:   '.',
	Delimiter: ',',
	Minor:     100,
}
