// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
package currency

// CNY is the Chinese Renminbi Yuan Currency
var CNY = Currency{
	Code:      "CNY",
	Number:    156,
	Symbol:    '¥',
	Decimal:   '.',
	Delimiter: ',',
	Minor:     100,
}
