// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
package currency

// MXN is the Mexican Peso Currency
var MXN = Currency{
	Code:      "MXN",
	Number:    484,
	Symbol:    '$',
	Decimal:   '.',
	Delimiter: ',',
	Minor:     100,
}
