// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
package currency

// Table holds all compiled currencies in a map ISO-NAME => value
var Table = map[string]Currency{
	"USD": USD,
	"MXN": MXN,
	"CNY": CNY,
	"CAD": CAD,
}
