// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
package currency

// USD is the United States Dollar Currency
var USD = Currency{
	Code:      "USD",
	Number:    840,
	Symbol:    '$',
	Decimal:   '.',
	Delimiter: ',',
	Minor:     100,
}
